config/routes.rb
Rails.application.routes.draw do
 

  get 'sessions/new'

  
get "log_in" => "sessions#new", :as => "log_in"

get "log_out" => "sessions#destroy", :as => "log_out"

 get 'tweets/set_a' => 'tweets#set_a'
 get 'tweets/upload' => 'tweets#upload'
 get 'tweets/category' => 'tweets#category'
 post 'tweets/setglobal' => 'tweets#setglobal'
 get "sign_up" => "users#new", :as => "sign_up"
 get 'tweets/moreinfo' => 'tweets#moreinfo'
 
 resources :users
 resources :sessions
resources :tweets do
    collection { post :import }
  end


   root 'tweets#category'








end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_one :tweet_category

  require 'CSV'
  
  
 
  def self.import(file, tweet_category)
  CSV.foreach(file.path, headers: true) do |row|
	 puts tweet_category[:id]
	# tweet_time, tweet_content, tweet_fromuser = row
	 puts row[0]
	 #binding.pry
	 tweet = Tweet.new
	 tweet.time = row[1]
	 tweet.content = row[0]
	 tweet.fromUser = row[2]
	 tweet.name= row[3]
	 tweet.profileimg= row[4]
	 tweet.tweet_category_id = tweet_category[:id]
	 tweet.save!
	 #tweet.create!(tweet_time,tweet_content,tweet_fromuser,tweet_category)
	 
  
     # tweet_hash = row.to_hash 
      #tweet = Tweet.where(id: tweet_hash["id"])
 
     #if tweet.count == 1
     #  tweet.first.update_attributes(tweet_hash)
     # else
     #  tweet.create!(tweet_hash)
     # end # end if !twwet.nil?
    end # end CSV.foreach
  end # end self.import(file)
end # end class



app/models/tweet_category.rb
class TweetCategory < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
 

  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
	flash.now[:error] = 'Unknown user. Please check your username and password.'
	#redirect_to root_url, :notice => "Logged in!"
	render "new"
	#flash[:notice] = 'Invalid email or password'
  #  flash.now.alert = "Invalid email or password"
    
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
 $global_var = 1
 #before_filter :set_counter
 $counter = 0
 def index
  $counter = 0
  @tweets = Tweet.order(:time => :desc)
  session[:ids] = @tweets
	respond_to do |format|
	 format.html 
		format.json { render json: @tweets }
end
end

def create
@tweet = Tweet.new
respond_to do |format|
	format.html 
	format.js
	end
 end
   
def show
@tweet = Tweet.find(params[:id])
render layout: false, json: @tweet
end

 def import
    #if !params[:upload].blank?    
	tweet_category = TweetCategory.find_by(name: params[:title])
	if tweet_category.nil?
		tweetcat = TweetCategory.new
		tweetcat.name = params[:title]
		tweetcat.description = params[:desc]
		tweetcat.save!
		tweet_category = TweetCategory.find_by(name: params[:title])
		#redirect_to root_url, :notice => "Messages Imported!"
	end
	begin
	Tweet.import(params[:file],tweet_category)
	redirect_to root_url, :notice => "Messages Imported!"
	rescue
    redirect_to tweets_upload_path, notice: "Invalid CSV file format."
	end
	#end
	#respond_to do |format|
	#format.html 
	#format.json
	#end
  end
 def setglobal
	var = params["edit"].keys
	
	$global_var = var
	redirect_to tweets_url
	
	#redirect_to root_url, notice: "Tweets imported."

 end
 def eachcat
	@catdata = Tweet.where(tweet_category_id: 2)
 end
 def category
	@data = TweetCategory.all
 end
 def upload
 end
 
 def set_counter
  puts "abcdefgh"
  @counter = 0 
   end
  
  def set_a
  puts params[:id]
  @twee = Tweet.where(tweet_category_id: $global_var)
  @oldesttweet = @twee.last
  render layout: false, json: @twee[$counter]
  $counter = $counter + 1
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.valid?
    @user.save
    session[:user_id] = @user.id
    redirect_to root_url, :notice => "Signed up!"
  else
    flash.now[:notice] = 'Please enter vaild details'
    render "new"
  end
end

 private

  def user_params
    params.require(:user).permit(:email, :password, :password_salt)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
respond_to :xml, :json
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dataset</title>
  <%= stylesheet_link_tag    'tweet', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'tweet', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--<div id="user_nav">-->
 <!-- <% if current_user %>-->
  <!--  Logged in as <%= current_user.email %>.-->
  <!--  <%= link_to "Log out", log_out_path %>-->
  <!--<% else %>-->
   <!-- <%= link_to "Sign up", sign_up_path %> or-->
   <!-- <%= link_to "log in", log_in_path %>-->
 <!-- <% end %>-->
<!--</div>-->

<!--<% flash.each do |name, msg| %>-->
 <!-- <%= content_tag :div, msg, :id => "flash_#{name}" %>-->
<!--<% end %>-->
<%= yield %> 

</body>
</html>

app/views/tweets/category.html.erb


<html>
<head>
<style>
body{
border-style: solid;
    border-width: 2px;	
}
h1.one {
    border-style: solid;
    border-width: 5px;
	margin-right: 100px;
	margin-bottom: 0px;
    margin-left: 90px;
	background-color: #33CCFF;
	color: white;
	text-align: center;
}

h2 {
	margin-top: 60px;
    margin-bottom: 0px;
	 margin-right: 90px;
    margin-left: 80px;
	font-family : serif;
   font-style: italic;
   color: #CC00CC;
   line-height: 100%;
   
   text-align: center;
}

p.link {
margin-top: 80px;
    margin-bottom: 0px;
   margin-right: 100px;
    margin-left: 90px;
    line-height: 200%;
	text-align: center;
}


#button1 {float:left; }
#button {float:right; }

#help{
	display : none;
	color: #33CCFF;
	font-family : serif;
    font-style: italic;
    font-weight: normal;
	
	}
#userdetails{
margin-top: 20px;
    margin-bottom: 30px;
   margin-right: 100px;
   color: #33CCFF;
    margin-left: 10px;
    line-height: 200%;
	text-align: center;
}
#x
{
color:black;
background:#EAF2D3;
height: 200px;
align: center;
margin-left: 100px;
margin-right: 90px;
font-size : 20px;
border-collapse: collapse;
 border: 1px solid black;
}




#button{
   border: 1px solid #0a3c59;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#65a9d7), to(#3e779d));
   background: -webkit-linear-gradient(top, #65a9d7, #3e779d);
   background: -moz-linear-gradient(top, #65a9d7, #3e779d);
   background: -ms-linear-gradient(top, #65a9d7, #3e779d);
   background: -o-linear-gradient(top, #65a9d7, #3e779d);
   background-image: -ms-linear-gradient(top, #65a9d7 0%, #3e779d 100%);
   padding: 10.5px 21px;
   -webkit-border-radius: 6px;
   -moz-border-radius: 6px;
   border-radius: 6px;
   -webkit-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   -moz-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   text-shadow: #7ea4bd 0 1px 0;
   
   font-size: 14px;
   font-family: helvetica, serif;
   text-decoration: none;
   vertical-align: middle;
   }
#button:hover {
   border: 1px solid #0a3c59;
   text-shadow: #1e4158 0 1px 0;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#65a9d7), to(#3e779d));
   background: -webkit-linear-gradient(top, #65a9d7, #3e779d);
   background: -moz-linear-gradient(top, #65a9d7, #3e779d);
   background: -ms-linear-gradient(top, #65a9d7, #3e779d);
   background: -o-linear-gradient(top, #65a9d7, #3e779d);
   background-image: -ms-linear-gradient(top, #65a9d7 0%, #3e779d 100%);
   color: #fff;
   }
#button:active {
   text-shadow: #1e4158 0 1px 0;
   border: 1px solid #0a3c59;
   background: #65a9d7;
   background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#3e779d));
   background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
   background: -moz-linear-gradient(top, #3e779d, #65a9d7);
   background: -ms-linear-gradient(top, #3e779d, #65a9d7);
   background: -o-linear-gradient(top, #3e779d, #65a9d7);
   background-image: -ms-linear-gradient(top, #3e779d 0%, #65a9d7 100%);
   color: #fff;
   }

</style>
<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$("button1").click(function(){
$("#help").fadeToggle("slow","linear");
});
});

</script>

</head>
<body>


<h1 class="one">Crisis Social Media Trainer</h1>

<h2 > Crisis Social Media Trainer is a tool that helps emergency responders practice monitoring social
media in a non-emergency setting. The goal of this tool is to help emergency responders 
understand the types of information they might encounter over social media during an 
emergency event.</h2>

<br/>

<br />
<br />
<p id="help" >Sometimes organizations are not prepared, nor organized for social media crisis. In this
application, Crisis Social Media Trainer role-play help agencies those with less experience 
of Social Media Crisis handling. Ultimate goal of this tool is to understand what information 
will be needed so you can plan ahead and learn how to make social media integral part of any 
communication response.</p>
<!--<h3 id="linknew"><%= link_to 'Upload New Dataset', new_tweet_path %> </h3>-->

<% if current_user %>
    <p id="userdetails">Logged in as <%= current_user.email %>.</p>
<% end %>
<div class="container">

<% if current_user %>
    <!--<p id="userdetails">Logged in as <%= current_user.email %>.</p>-->
<table style= "width:90%; text-align:center;margin-left:0px;margin-bottom:20px;">
  <tr>
    <td><div align= "center" style="margin-left: 20px; display:inline;"><button1 title="click to see about the app"><%= image_tag("help.jpg",:size =>"80x80") %></button1></div></td>
    <td><div align= "center" style="margin-left: 20px;margin-bottom:0px; display: inline;"><%= link_to image_tag("upload.png",:size =>"80x80", :border => 0, :alt => 'upload',title: 'click to insert a dataset', rel: 'tooltip'),tweets_upload_path %></div></td>
    <td><div align= "center" style="margin-left: 20px; display:inline;"><%= link_to image_tag("logout.jpg",:size =>"80x80", :border => 0, :alt => 'Logout',title: 'click to Logout', rel: 'tooltip' ),log_out_path %></div></td>
  </tr>
</table>
<% else %>
<table style= "width:90%; text-align:center;margin-left:0px;margin-bottom:20px;">
  <tr>
	<td><div style= "margin-left:0px;" ><%= link_to image_tag("Login.jpg",:size =>"170x170", :border => 0, :alt => 'login',title: 'click to LogIn', rel: 'tooltip'),new_session_path %></div></td>
	<td><div  ><button1 title="click to see about the app"><%= image_tag("help.jpg",:size =>"170x170") %></button1></div></td>
  </tr>
  </table>
	<% end %>

</div>
	
<table id="x" style= "width: 80%; text-align:center;margin-left:130px;margin-bottom:120px;border: 1px solid black;">
<colgroup><col /><col /><col /><col /></colgroup>
 <%= form_tag tweets_setglobal_path, multipart: true do %>

    <tr>
       <th style= " border: 1px solid black;">Name</th>
	   <th style= " border: 1px solid black;">Description</th>
	   <th style= " border: 1px solid black;">View</th>
	   
       </tr>
	  <% @data.each do |datae| %>       
  <tr>
    <td style= " border: 1px solid black;"><%= datae.name %></td>  
    <td style= " border: 1px solid black;"><%= datae.description %></td>  
	<td id="button"><%= submit_tag 'View Data', :name => "edit[#{datae.id}]"%><br></td>
  </tr>
<% end %>                       
</table>
	

<% end %> 
  
 
</body>
</html>






app/views/tweets/index.html.erb


<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<!DOCTYPE html>
<html>
<head>
<h1 class="one">Crisis Social Media Trainer </h1>
</head>
<style>

table, th, td {
    border: 1px solid grey;
}
td{
padding: 10px;
}
#x
{
color:black;
background:#EAF2D3;

height: 200px;
align: center;
margin-left: 100px;
margin-right: 90px;
}
#head{color:red;font:arial;font-size: 2em;background:black}
#myRow{color:black;font:arial;font-size: 1.1em;background:#EAF2D3}

html {
	margin: 0;
	padding: 0;
	border: 0;
}

body,div,h1,table,tbody,thead,tr,th,td	
{
	margin: 15;
	padding: 50;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}

table {
	border-collapse: separate;
	border-spacing: 20;
	height : 200px;
	align: center;
}


table,th,td {
	vertical-align: middle;
	
}
h1.one {
    border-style: solid;
    border-width: 5px;
	margin-right: 100px;
    margin-left: 90px;
	margin-top: 30px;
    margin-bottom: 0px;
	background-color: #33CCFF;
	color: white;
	font-weight: bold;
	font-size : 33px;
	text-align: center;
}
body{
    border-style: solid;
    border-width: 2px;
	padding-bottom: 40px;
	}
#link
{
  
   text-align: left;
}
span.spacing {
    padding-left: 9px;
    margin-left: 9px;
    height: 10px;
    border-left: 1px solid @border-color;
}
div.tweetwrapper {
    padding: 15px 0;
    border-bottom: 1px solid @border-color;
&:last-child {
    border: none;
}
}
#Home
{
text-align: right;
}
#view
{
text-align: center;
}
#userdetails,h3{
margin-top: 30px;
    margin-bottom: 0px;
   margin-right: 100px;
   color: #33CCFF;
    margin-left: 90px;
    line-height: 200%;
	text-align: center;
}
h3{color: #CC00CC;}
img.avatar {
    margin: 0 200px 0 20px;
    float: left;
}

p.avatar {
    margin: 50px 100px 0 90px;
    padding: 0;
    text-align: justify;
    line-height: 1.5;
    .antialiased(@text-color);
}

span.tweetwrapper {
    &.name {
        font-size: 18px;
        color: #58B84E;
    }
 
    &.time {
        font-size: 12px;
        color: #CCC;
    }
}

.wrapper {
    margin-left:0px;
}

.button {
    position: absolute:
    top: 50%;
}


#logout{
margin-bottom:0px;
margin-left:0px;}

.play{
   border: 1px solid #0a3c59;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#65a9d7), to(#3e779d));
   background: -webkit-linear-gradient(top, #65a9d7, #3e779d);
   background: -moz-linear-gradient(top, #65a9d7, #3e779d);
   background: -ms-linear-gradient(top, #65a9d7, #3e779d);
   background: -o-linear-gradient(top, #65a9d7, #3e779d);
   background-image: -ms-linear-gradient(top, #65a9d7 0%, #3e779d 100%);
   padding: 10.5px 21px;
   -webkit-border-radius: 6px;
   -moz-border-radius: 6px;
   border-radius: 6px;
   -webkit-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   -moz-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   text-shadow: #7ea4bd 0 1px 0;
   
   font-size: 14px;
   font-family: helvetica, serif;
   text-decoration: none;
   vertical-align: middle;
   }
.play:hover {
   border: 1px solid #0a3c59;
   text-shadow: #1e4158 0 1px 0;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#65a9d7), to(#3e779d));
   background: -webkit-linear-gradient(top, #65a9d7, #3e779d);
   background: -moz-linear-gradient(top, #65a9d7, #3e779d);
   background: -ms-linear-gradient(top, #65a9d7, #3e779d);
   background: -o-linear-gradient(top, #65a9d7, #3e779d);
   background-image: -ms-linear-gradient(top, #65a9d7 0%, #3e779d 100%);
   color: #fff;
   }
.play:active {
   text-shadow: #1e4158 0 1px 0;
   border: 1px solid #0a3c59;
   background: #65a9d7;
   background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#3e779d));
   background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
   background: -moz-linear-gradient(top, #3e779d, #65a9d7);
   background: -ms-linear-gradient(top, #3e779d, #65a9d7);
   background: -o-linear-gradient(top, #3e779d, #65a9d7);
   background-image: -ms-linear-gradient(top, #3e779d 0%, #65a9d7 100%);
   color: #fff;
   }


</style>
<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript">

function change() // no ';' here
{
    var elem = document.getElementById("myrow");
    if (elem.value==" play") elem.value = "pause";
    else if(elem.value = "pause") elem.value = " play";
}

function myFunction(resp)
{
     var tblBody = document.getElementById("myRow");
		var row = tblBody.insertRow(0);
		var a= row.insertCell(0);
		a.innerHTML= '<img src ="' + resp.profileimg + '" alt = "Image Not Found"  style="border:3px;height:80px;width:80px;float: left">' ;
		var x= row.insertCell(1); 
		x.innerHTML= '<div style="color:SkyBlue;font-size:20px">'+ resp.fromUser+'</div>'+ '<div style="color:darkblack;font-size:20px">' + resp.content+ '</div>' +'<p style="color:grey;font-size:15px" align = "right">' + resp.time + '</p>';
		var text = resp.content;
		var n = text.search("http");
		x.innerHTML+= n;
		//x.innerHTML+= <a href=n>clickhere</a> 
while (tblBody.rows.length>20)
	{
		document.getElementById("x").deleteRow(-1);
	}
}
var myVar;
function getText()
{
 $.ajax({
      type: "GET",
	   url: "/tweets/set_a",
	   dataType: "json",
      success:function(resp) {
	  if(resp == null)
		{
		  myVar.clearInterval();
		}
		myFunction(resp);
		return false;
		},
      error: function(data) {
	    alert("there is an error");
        return false;
	}
});       
}

window.onload = function()
{
var isPaused = false;
var time = 0;
var myVar = null; 
myVar= setInterval(function(){
if(!isPaused) getText()
}, 4000);
$('.play').on('click', function(e) {
    e.preventDefault();
    isPaused = !isPaused;
});
}

</script>

</head>

<body>
<h3>On this page, social media messages from the selected emergency event scroll down the page 
in the order they were sent. You may pause, resume, or restart the flow of messages.</h3>
<% if current_user %>
<p id="userdetails">Logged in as <%= current_user.email %>.</p>
<% end %>
	<div id="nav">
	<% if current_user %>
	<table style= "width:90%; text-align:center;margin-left:0px;margin-bottom:0px;">
  <tr>
    <td><div id = "three"><%= link_to image_tag("restart.png",:size =>"60x60", :border => 0, :alt => 'view', title: 'Restart tweets from the beggining', rel: 'tooltip'),{ controller: "tweets"} %></div></td>
	 <td><div class="wrapper" style="margin-left:10px;"><input id="myrow" onclick="change()" type="button" title="click to play/pause flow of tweets" value="pause" class="play"></div></td>
	 <td><div id = "one"><%= link_to image_tag("upload.png",:size =>"70x70", :border => 0, :alt => 'newdataset',title: 'click to upload a dataset', rel: 'tooltip' ),tweets_upload_path  %></div></td>
    <td><div id = "two"><%= link_to image_tag("11.png",:size =>"60x60", :border => 0, :alt => 'HOME', title: 'redirects to Home page', rel: 'tooltip'),root_url %></div> </td>
	<td><p id="logout"><%= link_to image_tag("logout.jpg",:size =>"80x80", :border => 0, :alt => 'logout',title: 'click to logout', rel: 'tooltip'),log_out_path  %></p></td>
	</tr>
</table>
    
    <% else %>
	<table style= "width:90%; text-align:center;margin-left:0px;margin-bottom:0px;">
	<tr>
	<td><div style="margin-left:0px;"><%= link_to image_tag("Login.jpg",:size =>"130x130", :border => 0, :alt => 'LogIn', title: 'click to login', rel: 'tooltip'),new_session_path %></div><td>
	<td><div class="wrapper" style="margin-left:0px;"><input id="myrow" onclick="change()" type="button" title="click to play/pause flow of tweets" value="pause" class="play"></div></td>
    <td><div id = "two"><%= link_to image_tag("11.png",:size =>"70x70", :border => 0, :alt => 'HOME', title: 'redirects to Home page', rel: 'tooltip'),root_url %></div> </td>
	<td><div id = "three"><%= link_to image_tag("restart.jpg",:size =>"90x90", :border => 0, :alt => 'view', title: 'Restart tweets from the beggining', rel: 'tooltip'),{ controller: "tweets"} %></div></td>
	</tr>
	</table>
	<% end %>
	</div>
	<div style="overflow: auto; height: 640px; width: 90%">

<table id="x" style= "width: 90%;margin-top:0px;">
<colgroup><col /><col /><col /><col /><col /><col /></colgroup>
   <tbody id="myRow">
    </tbody>
</table>

<!--
<div class="tweetwrapper" id="myRow" >
        <div id="myimg"></div>
        <p div ="mycont"> </p>
        <span class="name"><div id="myDIV"></div></span> <span class="time"><div id="myP"></div></span>
        
</div>
-->

</div>
<pre>
</pre>


</body>

</html>






app/views/tweets/new.html.erb




<%= render 'file' %>


<p><%= link_to 'View Data', tweets_path, class: 'button1' %></p>
<div align= "right" style="margin-right: 20px;"><%= link_to image_tag("11.png",:size =>"60x60", :border => 0, :alt => 'HOME', :title => ''),tweets_category_path %></div>
<style>

.button1{
   border: 1px solid #0a3c59;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#65a9d7), to(#3e779d));
   background: -webkit-linear-gradient(top, #65a9d7, #3e779d);
   background: -moz-linear-gradient(top, #65a9d7, #3e779d);
   background: -ms-linear-gradient(top, #65a9d7, #3e779d);
   background: -o-linear-gradient(top, #65a9d7, #3e779d);
   background-image: -ms-linear-gradient(top, #65a9d7 0%, #3e779d 100%);
   padding: 10.5px 21px;
   -webkit-border-radius: 6px;
   -moz-border-radius: 6px;
   border-radius: 6px;
   -webkit-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   -moz-box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   box-shadow: rgba(255,255,255,0.4) 0 1px 0, inset rgba(255,255,255,0.4) 0 1px 0;
   text-shadow: #7ea4bd 0 1px 0;
   color: #06426c;
   font-size: 14px;
   font-family: helvetica, serif;
   text-decoration: none;
   vertical-align: middle;
   }
.button1:hover {
   border: 1px solid #0a3c59;
   text-shadow: #1e4158 0 1px 0;
   background: #3e779d;
   background: -webkit-gradient(linear, left top, left bottom, from(#65a9d7), to(#3e779d));
   background: -webkit-linear-gradient(top, #65a9d7, #3e779d);
   background: -moz-linear-gradient(top, #65a9d7, #3e779d);
   background: -ms-linear-gradient(top, #65a9d7, #3e779d);
   background: -o-linear-gradient(top, #65a9d7, #3e779d);
   background-image: -ms-linear-gradient(top, #65a9d7 0%, #3e779d 100%);
   color: #fff;
   }
.button1:active {
   text-shadow: #1e4158 0 1px 0;
   border: 1px solid #0a3c59;
   background: #65a9d7;
   background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#3e779d));
   background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
   background: -moz-linear-gradient(top, #3e779d, #65a9d7);
   background: -ms-linear-gradient(top, #3e779d, #65a9d7);
   background: -o-linear-gradient(top, #3e779d, #65a9d7);
   background-image: -ms-linear-gradient(top, #3e779d 0%, #65a9d7 100%);
   color: #fff;
   }


</style>



app/views/tweets/set_a.js.erb
$('#x').append( <%= simple_format (j @oldesttweet.fromUser) %>)


app/views/tweets/show.html.erb

<p>
  <strong>Time:</strong>
  <%= @tweet.time %>
</p>
 
<p>
  <strong>content:</strong>
  <%= @tweet.content %>
</p>
<p>
  <strong>fromUser:</strong>
  <%= @tweet.fromUser %>
</p>

<%= link_to 'Back to Tweets', tweets_path %>


 

app/views/tweets/show.js.erb
$("#show").html("<%= escape_javascript(render('tweets/show')) %>")